const costDrivers = {
  SOFTWARE_RELIABILITY: 'SOFTWARE_RELIABILITY',
  DATABASE_SIZE: 'DATABASE_SIZE',
  PRODUCT_COMPLEXITY: 'PRODUCT_COMPLEXITY',
  RT_PERFORMANCE: 'RT_PERFORMANCE',
  MEMORY: 'MEMORY',
  VMENV_VOLATILITY: 'VMENV_VOLATILITY',
  TURNABOUT_TIME: 'TURNABOUT_TIME',
  ANALYST_CAPABILITY: 'ANALYST_CAPABILITY',
  APPLICATIONS_EXPERIENCE: 'APPLICATIONS_EXPERIENCE',
  SE_CAPABILITY: 'SE_CAPABILITY',
  VM_EXPERIENCE: 'VM_EXPERIENCE',
  PLANG_EXPERIENCE: 'PLANG_EXPERIENCE',
  SE_METHODS_APPLICATION: 'SE_METHODS_APPLICATION',
  SW_TOOLS_USE: 'SW_TOOLS_USE',
  DEV_SCHEDULE: 'DEV_SCHEDULE',
};

export default costDrivers;
